version: '3.7'
networks:
  laravel_jwt:
services:
  app:
    build:
      context: .
      dockerfile: .docker/php-apache.dockerfile
    image: 'laravel-jwt-products'
    container_name: laravel_vue_app
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
    networks:
    - laravel_jwt
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    networks:
     - laravel_jwt
    ports:
      - "3306:3306"
     # - "${DB_PORT}:3306"  Geting port from .env file
    environment:
      #MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_DATABASE: 'laravel_jwtauth'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
     # MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ""
    volumes:
        - ./db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    restart: always
    networks:
     - laravel_jwt
    ports:
      - 8183:80
    environment:
      - PMA_HOST=db
      - UPLOAD_LIMIT=1G